use anyhow::{bail, Context, Result};
use crate::config::{CoreConfig, SystemConfig};
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use super::full_scan::full_scan;
use super::CORE_TOML;

/// Integrity check — runs before every `cordon run`.
///
/// NON-INTERACTIVE. Does NOT write to system.toml under normal conditions.
/// Only checks what is already IN system.toml — nothing more.
///
/// Key design principle:
///   The user chose what to include during the full scan.
///   We do NOT care about modules that are absent from system.toml.
///   We ONLY care that what IS in system.toml still exists on disk.
///
/// Triggers a full scan (with user interaction) when:
///   - system.toml is missing
///   - system.toml is malformed / unreadable
///   - Binary version doesn't match system.toml version
///   - A verified mount's path no longer exists on disk
///
/// Hard blocks (no scan, just error) when:
///   - A foreign entry is found in system.toml
///   - --network is requested but required network modules are absent/unverified
///   - --gui is requested but required GUI modules are absent/unverified
pub fn integrity_check(network: bool, gui: bool) -> Result<SystemConfig> {
    let system_path = crate::config::get_config_dir()?.join("system.toml");

    // ── Step 1: Parse system.toml
    //
    // If it doesn't exist at all: first-time user, run the full scan.
    // If it exists but can't be parsed: something went wrong (hand-edit,
    // partial write, etc.) — safest action is a fresh full scan.
    if !system_path.exists() {
        println!("📝 system.toml not found — running initial scan...");
        full_scan()?;
    }

    let content = fs::read_to_string(&system_path).unwrap_or_default();

    let mut config: SystemConfig = match toml::from_str(&content) {
        Ok(c) => c,
        Err(e) => {
            println!("⚠️  system.toml is malformed — re-running full scan.");
            println!("   (reason: {})", e);
            full_scan()?;
            let fresh = fs::read_to_string(&system_path)?;
            toml::from_str(&fresh)?
        }
    };

    // ── Step 2: Version check
    //
    // Why: core.toml is compiled into the binary. When Cordon is updated,
    // core.toml may have new modules, removed modules, or renamed fields.
    // A system.toml generated by an older binary may be stale or incompatible.
    // Safest action: trigger a fresh full scan.
    let current_version = env!("CARGO_PKG_VERSION");
    if config.cordon_version != current_version {
        println!(
            "🔄 Cordon updated ({} → {}) — re-running scan for the new version...",
            config.cordon_version, current_version
        );
        full_scan()?;
        let fresh = fs::read_to_string(&system_path)?;
        config = toml::from_str(&fresh)?;
    }

    // ── Step 3: Foreign entry check
    //
    // system.toml is ONLY for entries that correspond to core.toml modules.
    // If there's an entry we don't recognise, something is wrong:
    //   - User hand-edited system.toml and added a custom path
    //   - File was tampered with
    // Either way: hard block. Custom mounts belong in cordon.toml (user.toml).
    let core: CoreConfig = toml::from_str(CORE_TOML)
        .context("Failed to parse embedded core.toml")?;

    let core_names: HashSet<&str> = core.modules.iter()
        .map(|m| m.name.as_str())
        .collect();

    for mount in &config.mounts {
        if !core_names.contains(mount.name.as_str()) {
            bail!(
                "Security: foreign entry '{}' found in system.toml.\n\
                 system.toml must only contain modules defined in core.toml.\n\
                 To add custom paths, use cordon.toml (user.toml) instead.\n\
                 To regenerate a clean system.toml: cordon scan",
                mount.name
            );
        }
    }

    // ── Step 4: File existence check
    //
    // For each VERIFIED mount in system.toml, check that its source path
    // still exists on disk. Paths can break after:
    //   - System upgrades (library paths change)
    //   - Package removal
    //   - Distro migration
    //
    // We skip UNVERIFIED mounts — those were already flagged at scan time
    // and the user was told about them. No point re-checking known-broken paths.
    //
    // On failure: trigger a full scan. The user gets to re-confirm their choices.
    let mut broken: Vec<String> = Vec::new();

    for mount in &config.mounts {
        if !mount.verified {
            continue; // Already known-missing from scan time — skip.
        }

        let exists = if mount.bind_type == "symlink" {
            // Symlink entry: src is the link target (e.g. "usr/bin").
            // We verify the TARGET exists, not the symlink itself.
            // Relative targets (like "usr/bin") are resolved from "/".
            let target = PathBuf::from(&mount.src);
            let resolved = if target.is_absolute() {
                target
            } else {
                PathBuf::from("/").join(&target)
            };
            resolved.exists()
        } else {
            // Real directory: just check the src path exists.
            Path::new(&mount.src).exists()
        };

        if !exists {
            broken.push(mount.name.clone());
        }
    }

    if !broken.is_empty() {
        println!("⚠️  Paths no longer exist: {}", broken.join(", "));
        println!("   System may have changed since last scan — re-running full scan...");
        full_scan()?;
        let fresh = fs::read_to_string(&system_path)?;
        config = toml::from_str(&fresh)?;
    }

    // ── Step 5: Hard fail on --network
    //
    // If the user is requesting network mode, we check whether the required
    // network modules are actually in system.toml AND verified.
    //
    // "Not in system.toml" means the user didn't include network support during
    // the scan — they need to re-scan and answer 'y' to network support.
    //
    // "In system.toml but unverified" means the path existed at scan time but
    // the required files inside it were missing — also needs fixing.
    if network {
        for core_mod in core.modules.iter().filter(|m| m.when == "network" && m.required) {
            match config.mounts.iter().find(|m| m.name == core_mod.name) {
                None => bail!(
                    "❌ --network requires module '{}' but it is not in system.toml.\n\
                     Re-run `cordon scan` and answer 'y' to network support.",
                    core_mod.name
                ),
                Some(m) if !m.verified => bail!(
                    "❌ --network requires module '{}' but it failed verification.\n\
                     Impact: {}\n\
                     Re-run `cordon scan` to fix.",
                    core_mod.name, core_mod.functionality
                ),
                _ => {} // present and verified ✅
            }
        }
    }

    // ── Step 6: Hard fail on --gui
    //
    // Same logic as network. Required GUI modules must be in system.toml
    // and verified. If not, the user needs to re-scan with GUI support enabled.
    if gui {
        for core_mod in core.modules.iter().filter(|m| m.when == "gui" && m.required) {
            match config.mounts.iter().find(|m| m.name == core_mod.name) {
                None => bail!(
                    "❌ --gui requires module '{}' but it is not in system.toml.\n\
                     Re-run `cordon scan` and answer 'y' to GUI support.",
                    core_mod.name
                ),
                Some(m) if !m.verified => bail!(
                    "❌ --gui requires module '{}' but it failed verification.\n\
                     Impact: {}\n\
                     Re-run `cordon scan` to fix.",
                    core_mod.name, core_mod.functionality
                ),
                _ => {} // present and verified ✅
            }
        }
    }

    Ok(config)
}
